# Scikit Learn

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
    datasets_dir = r'..\..\python-ml-course-master\datasets'

### Eliminación de rasgos recursiva. Elimina las variables que menos aporten al modelo

In [8]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

In [9]:
filepath = datasets_dir + os.sep + r"ads/Advertising.csv"
data = pd.read_csv(filepath)
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [14]:
feature_cols = ["Radio", "TV", "Newspaper"]

In [15]:
X = data[feature_cols]
Y = data["Sales"]

In [16]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)  # Dos es la cantidad de variables que quiero. En este caso se que quiero quedarme con dos 
selector = selector.fit(X, Y)

C:\Users\USUARIO\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [17]:
selector.support_ # Cuales son las variables con las que me he quedado de feature_cols

array([ True,  True, False])

In [18]:
selector.ranking_

array([1, 1, 2])

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
X_pred = X[["TV", "Radio"]]

In [21]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [25]:
lm.intercept_ # Termino independiente

2.9210999124051362

In [26]:
lm.coef_ # Coefs

array([0.04575482, 0.18799423])

In [27]:
lm.score(X_pred, Y) # R2

0.8971942610828956